import { writeFile } from 'node:fs/promises';
import path from 'node:path';

const GITHUB_USER = process.env.GITHUB_USER ?? 'Ebycow';
const OUTPUT_FILE = path.resolve('src/github-projects.ts');
const INCLUDE_FORKS = process.env.GITHUB_INCLUDE_FORKS === '1';
const INCLUDE_ARCHIVED = process.env.GITHUB_INCLUDE_ARCHIVED === '1';
const MAX_PROJECTS = Number.parseInt(process.env.GITHUB_LIMIT ?? '', 10) || 0;

async function fetchJson(url) {
  const response = await fetch(url, {
    headers: {
      accept: 'application/vnd.github+json',
      'user-agent': 'ebycow.net build script',
      ...(process.env.GITHUB_TOKEN ? { authorization: `Bearer ${process.env.GITHUB_TOKEN}` } : {}),
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }

  return {
    data: await response.json(),
    link: response.headers.get('link') ?? '',
  };
}

function parseNextLink(linkHeader) {
  for (const part of linkHeader.split(',')) {
    const match = part.match(/<([^>]+)>;\s*rel="next"/);
    if (match) return match[1];
  }

  return '';
}

async function fetchRepos() {
  const repos = [];
  let url = `https://api.github.com/users/${encodeURIComponent(
    GITHUB_USER,
  )}/repos?type=owner&sort=created&direction=desc&per_page=100`;

  while (url) {
    const { data, link } = await fetchJson(url);
    if (!Array.isArray(data)) {
      throw new Error('GitHub repos response was not an array.');
    }

    repos.push(...data);
    url = parseNextLink(link);
  }

  const filteredRepos = repos.filter((repo) => {
    if (!INCLUDE_FORKS && repo.fork) return false;
    if (!INCLUDE_ARCHIVED && repo.archived) return false;
    return true;
  });

  return MAX_PROJECTS > 0 ? filteredRepos.slice(0, MAX_PROJECTS) : filteredRepos;
}

function formatCreatedDate(value) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;

  return new Intl.DateTimeFormat('ja-JP', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    timeZone: 'UTC',
  }).format(date);
}

function normalizeDescription(value) {
  return typeof value === 'string' ? value.replace(/\s+/g, ' ').trim() : '';
}

function toProject(repo) {
  return {
    id: `github-${repo.id}`,
    title: repo.name,
    createdAt: repo.created_at,
    createdAtLabel: formatCreatedDate(repo.created_at),
    url: repo.html_url,
    description: normalizeDescription(repo.description),
    language: repo.language ?? '',
    stars: String(repo.stargazers_count ?? 0),
    forks: String(repo.forks_count ?? 0),
    archived: Boolean(repo.archived),
  };
}

function serializeProjects(projects) {
  return `// Generated by scripts/fetch-github.mjs. Do not edit by hand.
export type GitHubProject = {
  id: string;
  title: string;
  createdAt: string;
  createdAtLabel: string;
  url: string;
  description: string;
  language: string;
  stars: string;
  forks: string;
  archived: boolean;
};

export const githubProjects: GitHubProject[] = ${JSON.stringify(projects, null, 2)};
`;
}

async function main() {
  const repos = await fetchRepos();
  const projects = repos.map(toProject);

  await writeFile(OUTPUT_FILE, serializeProjects(projects), 'utf8');
  console.log(`Fetched ${projects.length} GitHub projects into ${path.relative(process.cwd(), OUTPUT_FILE)}.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
