// Generated by scripts/fetch-bandcamp.mjs. Do not edit by hand.
export type BandcampWork = {
  id: string;
  title: string;
  releaseDate: string;
  releaseDateLabel: string;
  format: string;
  trackCount: string;
  image: string;
  url: string;
  description: string;
};

export const bandcampWorks: BandcampWork[] = [
  {
    "id": "album-1433171774",
    "title": "Graduated",
    "releaseDate": "07 Nov 2025 00:00:00 GMT",
    "releaseDateLabel": "2025/11/07",
    "format": "Album",
    "trackCount": "5",
    "image": "https://f4.bcbits.com/img/a3610154173_10.jpg",
    "url": "https://ebycow.bandcamp.com/album/graduated",
    "description": "Graduated."
  },
  {
    "id": "album-2061470840",
    "title": "Touchstones",
    "releaseDate": "10 May 2024 00:00:00 GMT",
    "releaseDateLabel": "2024/05/10",
    "format": "Album",
    "trackCount": "3",
    "image": "https://f4.bcbits.com/img/a1193337813_10.jpg",
    "url": "https://ebycow.bandcamp.com/album/touchstones",
    "description": "Churu contains red malt..."
  },
  {
    "id": "track-2858922442",
    "title": "青い海は何処",
    "releaseDate": "18 Aug 2023 00:00:00 GMT",
    "releaseDateLabel": "2023/08/18",
    "format": "Single",
    "trackCount": "1",
    "image": "https://f4.bcbits.com/img/a3694251691_10.jpg",
    "url": "https://ebycow.bandcamp.com/track/--25",
    "description": "ｺｺﾀﾞﾖ"
  },
  {
    "id": "album-996156954",
    "title": "Splitting",
    "releaseDate": "30 Dec 2022 00:00:00 GMT",
    "releaseDateLabel": "2022/12/30",
    "format": "Album",
    "trackCount": "2",
    "image": "https://f4.bcbits.com/img/a1269382516_10.jpg",
    "url": "https://ebycow.bandcamp.com/album/splitting",
    "description": ""
  },
  {
    "id": "album-3199149028",
    "title": "Shrimp's Crab Scallop",
    "releaseDate": "01 Nov 2022 09:53:34 GMT",
    "releaseDateLabel": "2022/11/01",
    "format": "Album",
    "trackCount": "3",
    "image": "https://f4.bcbits.com/img/a1587334015_10.jpg",
    "url": "https://ebycow.bandcamp.com/album/shrimps-crab-scallop",
    "description": "Nyan! Cat! Pat! You into the new world, it's the 'kitten world'. sadly you die because cat is so cute *pofun*. see you again. And, now... this EP include two artwork (different artwork and concept image) images can use in NovelAI. https://novelai.net Disappointed? this artwork drawn AI! MUSIC WAS MADE BY ME."
  },
  {
    "id": "album-3456913545",
    "title": "Iterable",
    "releaseDate": "08 Jul 2022 00:00:00 GMT",
    "releaseDateLabel": "2022/07/08",
    "format": "Album",
    "trackCount": "10",
    "image": "https://f4.bcbits.com/img/a2393760257_10.jpg",
    "url": "https://ebycow.bandcamp.com/album/iterable",
    "description": ""
  },
  {
    "id": "album-3729186972",
    "title": "Zurückkehren",
    "releaseDate": "14 May 2022 22:00:07 GMT",
    "releaseDateLabel": "2022/05/14",
    "format": "Album",
    "trackCount": "2",
    "image": "https://f4.bcbits.com/img/a0475923896_10.jpg",
    "url": "https://ebycow.bandcamp.com/album/zur-ckkehren",
    "description": ""
  },
  {
    "id": "album-2635661779",
    "title": "Sanction",
    "releaseDate": "24 Dec 2021 17:16:48 GMT",
    "releaseDateLabel": "2021/12/24",
    "format": "Album",
    "trackCount": "5",
    "image": "https://f4.bcbits.com/img/a2864037130_10.jpg",
    "url": "https://ebycow.bandcamp.com/album/sanction",
    "description": ""
  },
  {
    "id": "album-4206444029",
    "title": "Probability & Statistics",
    "releaseDate": "24 Dec 2021 16:27:36 GMT",
    "releaseDateLabel": "2021/12/24",
    "format": "Album",
    "trackCount": "5",
    "image": "https://f4.bcbits.com/img/a0457842652_10.jpg",
    "url": "https://ebycow.bandcamp.com/album/probability-statistics",
    "description": ""
  },
  {
    "id": "album-1630334605",
    "title": "M2",
    "releaseDate": "11 Jun 2021 00:00:00 GMT",
    "releaseDateLabel": "2021/06/11",
    "format": "Album",
    "trackCount": "10",
    "image": "https://f4.bcbits.com/img/a3874386137_10.jpg",
    "url": "https://ebycow.bandcamp.com/album/m2",
    "description": ""
  },
  {
    "id": "album-1044781971",
    "title": "Counterparty",
    "releaseDate": "10 Apr 2021 00:00:00 GMT",
    "releaseDateLabel": "2021/04/10",
    "format": "Album",
    "trackCount": "4",
    "image": "https://f4.bcbits.com/img/a3647257139_10.jpg",
    "url": "https://ebycow.bandcamp.com/album/counterparty",
    "description": ""
  },
  {
    "id": "track-500869619",
    "title": "疎通",
    "releaseDate": "11 Mar 2021 00:00:00 GMT",
    "releaseDateLabel": "2021/03/11",
    "format": "Single",
    "trackCount": "1",
    "image": "https://f4.bcbits.com/img/a1425584953_10.jpg",
    "url": "https://ebycow.bandcamp.com/track/--9",
    "description": ""
  },
  {
    "id": "track-2055250390",
    "title": "ねこのテーマ",
    "releaseDate": "30 Sep 2020 00:00:00 GMT",
    "releaseDateLabel": "2020/09/30",
    "format": "Single",
    "trackCount": "1",
    "image": "https://f4.bcbits.com/img/a1380973534_10.jpg",
    "url": "https://ebycow.bandcamp.com/track/--8",
    "description": ""
  },
  {
    "id": "album-3111022513",
    "title": "Roleplay",
    "releaseDate": "12 Feb 2021 00:00:00 GMT",
    "releaseDateLabel": "2021/02/12",
    "format": "Album",
    "trackCount": "4",
    "image": "https://f4.bcbits.com/img/a4278236737_10.jpg",
    "url": "https://ebycow.bandcamp.com/album/roleplay",
    "description": ""
  },
  {
    "id": "track-2745428504",
    "title": "Yakisoba no Aonori",
    "releaseDate": "01 Aug 2020 00:00:00 GMT",
    "releaseDateLabel": "2020/08/01",
    "format": "Single",
    "trackCount": "1",
    "image": "https://f4.bcbits.com/img/a1962041919_10.jpg",
    "url": "https://ebycow.bandcamp.com/track/yakisoba-no-aonori",
    "description": ""
  },
  {
    "id": "album-3920467175",
    "title": "Trip",
    "releaseDate": "01 Feb 2021 00:00:00 GMT",
    "releaseDateLabel": "2021/02/01",
    "format": "Album",
    "trackCount": "4",
    "image": "https://f4.bcbits.com/img/a2772552353_10.jpg",
    "url": "https://ebycow.bandcamp.com/album/trip",
    "description": ""
  },
  {
    "id": "album-839841160",
    "title": "L2",
    "releaseDate": "01 Jan 2021 00:00:00 GMT",
    "releaseDateLabel": "2021/01/01",
    "format": "Album",
    "trackCount": "10",
    "image": "https://f4.bcbits.com/img/a3630309075_10.jpg",
    "url": "https://ebycow.bandcamp.com/album/l2",
    "description": ""
  },
  {
    "id": "track-199716530",
    "title": "(⋈◍＞◡＜◍)",
    "releaseDate": "06 Dec 2019 00:00:00 GMT",
    "releaseDateLabel": "2019/12/06",
    "format": "Single",
    "trackCount": "1",
    "image": "https://f4.bcbits.com/img/a3323107468_10.jpg",
    "url": "https://ebycow.bandcamp.com/track/--5",
    "description": ""
  },
  {
    "id": "album-270618804",
    "title": "Kani",
    "releaseDate": "31 Oct 2020 00:00:00 GMT",
    "releaseDateLabel": "2020/10/31",
    "format": "Album",
    "trackCount": "5",
    "image": "https://f4.bcbits.com/img/a2522360657_10.jpg",
    "url": "https://ebycow.bandcamp.com/album/kani",
    "description": ""
  },
  {
    "id": "track-1060600042",
    "title": "彁",
    "releaseDate": "14 Dec 2019 00:00:00 GMT",
    "releaseDateLabel": "2019/12/14",
    "format": "Single",
    "trackCount": "1",
    "image": "https://f4.bcbits.com/img/a1555410800_10.jpg",
    "url": "https://ebycow.bandcamp.com/track/-",
    "description": ""
  }
];
