// Generated by scripts/fetch-github.mjs. Do not edit by hand.
export type GitHubProject = {
  id: string;
  title: string;
  createdAt: string;
  createdAtLabel: string;
  url: string;
  description: string;
  language: string;
  stars: string;
  forks: string;
  archived: boolean;
};

export const githubProjects: GitHubProject[] = [
  {
    "id": "github-1221929022",
    "title": "MMANA",
    "createdAt": "2026-04-26T21:24:01Z",
    "createdAtLabel": "2026/04/26",
    "url": "https://github.com/Ebycow/MMANA",
    "description": "JE3HHT 森OMが作成された、Windows上で動作するアンテナ設計解析プログラムです。",
    "language": "C++",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-1220986125",
    "title": "EDCBaseball",
    "createdAt": "2026-04-25T15:50:30Z",
    "createdAtLabel": "2026/04/25",
    "url": "https://github.com/Ebycow/EDCBaseball",
    "description": "EDCBの番組表データからプロ野球・MLB公式試合を一覧表示",
    "language": "Python",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-1216162175",
    "title": "SillyTavern-Irodori-TTS-Extension",
    "createdAt": "2026-04-20T16:21:49Z",
    "createdAtLabel": "2026/04/20",
    "url": "https://github.com/Ebycow/SillyTavern-Irodori-TTS-Extension",
    "description": "",
    "language": "JavaScript",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-1210207434",
    "title": "Twitch-VOD-toText",
    "createdAt": "2026-04-14T07:29:22Z",
    "createdAtLabel": "2026/04/14",
    "url": "https://github.com/Ebycow/Twitch-VOD-toText",
    "description": "",
    "language": "Python",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-1192799263",
    "title": "TVTest-MCPServer",
    "createdAt": "2026-03-26T15:15:59Z",
    "createdAtLabel": "2026/03/26",
    "url": "https://github.com/Ebycow/TVTest-MCPServer",
    "description": "",
    "language": "Python",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-1191805753",
    "title": "TVTestHTTPPlugin",
    "createdAt": "2026-03-25T15:50:44Z",
    "createdAtLabel": "2026/03/25",
    "url": "https://github.com/Ebycow/TVTestHTTPPlugin",
    "description": "TVTest の HTTP REST API プラグイン",
    "language": "C++",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-1191386488",
    "title": "EDCB-MCPServer",
    "createdAt": "2026-03-25T07:32:57Z",
    "createdAtLabel": "2026/03/25",
    "url": "https://github.com/Ebycow/EDCB-MCPServer",
    "description": "",
    "language": "TypeScript",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-1173267825",
    "title": "TVTest-Discord-Bot",
    "createdAt": "2026-03-05T07:18:57Z",
    "createdAtLabel": "2026/03/05",
    "url": "https://github.com/Ebycow/TVTest-Discord-Bot",
    "description": "",
    "language": "TypeScript",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-1166542438",
    "title": "iruyo",
    "createdAt": "2026-02-25T10:36:02Z",
    "createdAtLabel": "2026/02/25",
    "url": "https://github.com/Ebycow/iruyo",
    "description": "Twitchユーザが配信にコメントしたら通知するツール",
    "language": "TypeScript",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-1164013021",
    "title": "twicome",
    "createdAt": "2026-02-22T14:04:23Z",
    "createdAtLabel": "2026/02/22",
    "url": "https://github.com/Ebycow/twicome",
    "description": "Twitch VOD コメント検索・分析ツール",
    "language": "Python",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-1140761677",
    "title": "famista",
    "createdAt": "2026-01-23T18:15:28Z",
    "createdAtLabel": "2026/01/23",
    "url": "https://github.com/Ebycow/famista",
    "description": "",
    "language": "Python",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-545959787",
    "title": "shima-rinversion",
    "createdAt": "2022-10-05T09:21:05Z",
    "createdAtLabel": "2022/10/05",
    "url": "https://github.com/Ebycow/shima-rinversion",
    "description": "textual inversion of shima rin",
    "language": "",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-523044251",
    "title": "grove-sketch",
    "createdAt": "2022-08-09T17:20:39Z",
    "createdAtLabel": "2022/08/09",
    "url": "https://github.com/Ebycow/grove-sketch",
    "description": "",
    "language": "",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-522896398",
    "title": "hanako-se-manager",
    "createdAt": "2022-08-09T10:08:00Z",
    "createdAtLabel": "2022/08/09",
    "url": "https://github.com/Ebycow/hanako-se-manager",
    "description": "",
    "language": "HTML",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-520995712",
    "title": "beat-saber-result-overlay",
    "createdAt": "2022-08-03T18:44:36Z",
    "createdAtLabel": "2022/08/03",
    "url": "https://github.com/Ebycow/beat-saber-result-overlay",
    "description": "",
    "language": "HTML",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-519967664",
    "title": "DiscordDayTraderGame",
    "createdAt": "2022-08-01T04:51:52Z",
    "createdAtLabel": "2022/08/01",
    "url": "https://github.com/Ebycow/DiscordDayTraderGame",
    "description": "",
    "language": "JavaScript",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-519443923",
    "title": "Shima-Skipper",
    "createdAt": "2022-07-30T06:58:44Z",
    "createdAtLabel": "2022/07/30",
    "url": "https://github.com/Ebycow/Shima-Skipper",
    "description": "dアニメストアでゆるキャン△のOP-EDを自動でスキップするユーザスクリプト",
    "language": "JavaScript",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-519415156",
    "title": "Endless-Shimarin",
    "createdAt": "2022-07-30T04:11:57Z",
    "createdAtLabel": "2022/07/30",
    "url": "https://github.com/Ebycow/Endless-Shimarin",
    "description": "dアニメストア無限しまりん",
    "language": "JavaScript",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-511359944",
    "title": "sarderly",
    "createdAt": "2022-07-07T02:41:59Z",
    "createdAtLabel": "2022/07/07",
    "url": "https://github.com/Ebycow/sarderly",
    "description": "Simple uploader by Node.js, for servers with too many storage",
    "language": "JavaScript",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-436240843",
    "title": "anime2vec",
    "createdAt": "2021-12-08T12:33:22Z",
    "createdAtLabel": "2021/12/08",
    "url": "https://github.com/Ebycow/anime2vec",
    "description": "MyAnimeList Database 2020 により学習されたアニメ作品の埋め込み表現",
    "language": "Python",
    "stars": "2",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-246281057",
    "title": "sacloud-ddns",
    "createdAt": "2020-03-10T11:18:58Z",
    "createdAtLabel": "2020/03/10",
    "url": "https://github.com/Ebycow/sacloud-ddns",
    "description": "さくらのクラウドDNS(アプライアンス)用のDDNSシステム",
    "language": "JavaScript",
    "stars": "1",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-237217025",
    "title": "hanako",
    "createdAt": "2020-01-30T13:18:14Z",
    "createdAtLabel": "2020/01/30",
    "url": "https://github.com/Ebycow/hanako",
    "description": "Discord 読み上げはなこ",
    "language": "JavaScript",
    "stars": "11",
    "forks": "1",
    "archived": false
  },
  {
    "id": "github-186214305",
    "title": "dAnimeList",
    "createdAt": "2019-05-12T05:11:33Z",
    "createdAtLabel": "2019/05/12",
    "url": "https://github.com/Ebycow/dAnimeList",
    "description": "dアニメストアで視聴中のアニメからMyAnimeListの当該ページへのショートカットを追加するユーザスクリプト",
    "language": "JavaScript",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-172647096",
    "title": "mastodon-masuo",
    "createdAt": "2019-02-26T05:53:23Z",
    "createdAtLabel": "2019/02/26",
    "url": "https://github.com/Ebycow/mastodon-masuo",
    "description": "Mastodon.socialのTLからPawooユーザのアイコンを表示できるようにするユーザスクリプト",
    "language": "TypeScript",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-164419255",
    "title": "mastodon-elona-aliasbot",
    "createdAt": "2019-01-07T10:56:51Z",
    "createdAtLabel": "2019/01/07",
    "url": "https://github.com/Ebycow/mastodon-elona-aliasbot",
    "description": "それは動いている",
    "language": "TypeScript",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-164026453",
    "title": "syamu",
    "createdAt": "2019-01-03T21:48:41Z",
    "createdAtLabel": "2019/01/03",
    "url": "https://github.com/Ebycow/syamu",
    "description": "引退しろ https://ebycow.github.io/syamu/",
    "language": "HTML",
    "stars": "1",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-154521798",
    "title": "ebycow.net",
    "createdAt": "2018-10-24T15:08:23Z",
    "createdAtLabel": "2018/10/24",
    "url": "https://github.com/Ebycow/ebycow.net",
    "description": "http://ebycow.net",
    "language": "TypeScript",
    "stars": "0",
    "forks": "0",
    "archived": false
  },
  {
    "id": "github-72276869",
    "title": "inm_difflist",
    "createdAt": "2016-10-29T09:45:59Z",
    "createdAtLabel": "2016/10/29",
    "url": "https://github.com/Ebycow/inm_difflist",
    "description": "淫夢BMS難易度表",
    "language": "HTML",
    "stars": "1",
    "forks": "0",
    "archived": false
  }
];
